In [1]:
import pandas as pd
import numpy as np
import scipy
from ColumnSet import ColumnSet
from MakeNumericColumns import MakeNumericColumns


import logging
import sys
logging.basicConfig(stream=sys.stdout, level=logging.INFO, datefmt='%H:%M:%S', format='%(asctime)s.%(msecs)03d - %(filename)s:%(lineno)d - %(message)s')

In [2]:
data1 = { 'country': ['Germany','Germany','Germany','Germany','Germany', 'Germany',
                     'US', 'US', 'US', 'US', 'US',
                     'UK', 'UK', 'UK', 'UK', 'UK', 
                     'LUX','LUX','LUX','LUX','LUX'],
         'currency':['EUR','EUR','EUR','EUR','EUR','MXN',
                     'USD','USD','USD','USD','USD',
                     'GBP','GBP','GBP','GBP','GBP',
                     'EUR','EUR','EUR','EUR','EUR'],
         'manyvalues':['A', 'A', 'B', 'B', 'C', 'C', 'D', 'D', 'E', 'E', 'E', 'K', 'L', 'M', 'N', 'O',
                      'Z', 'Z', 'Z', 'Z', 'Y'],
         'rand': [ np.random.uniform(100,200) for _ in range(21) ],
         'linear': [ x for x in range(21) ],
        'city': ['Frankfurt'] * 6 + ['LA'] * 5 + ['London'] * 5+  ['Luxembourg'] * 5}
data1 = pd.DataFrame(data1) 

cs = ColumnSet(data1)


mnc = MakeNumericColumns()

In [3]:

for column in cs.inputcolumns:
        print(mnc.Process(column))
        

[0 0 0 0 0 0 3 3 3 3 3 2 2 2 2 2 1 1 1 1 1]
[0 0 0 0 0 2 3 3 3 3 3 1 1 1 1 1 0 0 0 0 0]
[ 0  0  1  1  2  2  3  3  4  4  4  5  6  7  8  9 11 11 11 11 10]
[141.52666219 181.37911588 144.85630265 197.50305629 168.5555249
 102.50877097 197.98895887 155.94040875 101.49351165 185.14019101
 114.07458969 116.717294   167.05827128 109.75104339 134.56510328
 134.32136182 134.46775413 189.02194948 171.33814595 115.90843028
 161.46117781]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[0 0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3]


In [4]:
np_array = mnc.ProcessColumnSet(cs)

In [ ]:
print(np_array)

In [6]:
# Now with all the derived columns too.
cs.AddDerived()
np_array = mnc.ProcessColumnSet(cs)
print(np_array)

01:05:47.812 - resolver.py:105 - Using C:\Users\will\AppData\Local\Temp\tfhub_modules to cache modules.


country
currency
manyvalues
rand
linear
city
col: country.Len  parent: country
Name : country.Len
Size : 21
Dtype : int64
Depth : 1
Children: []
Parent: country
0    7
1    7
2    7
3    7
4    7
5    7
6    2
7    2
8    2
9    2
Name: country.Len, dtype: int64
col: country.TokenizerCharDecimal_characters1  parent: country
Name : country.TokenizerCharDecimal_characters1
Size : 21
Dtype : object
Depth : 1
Children: [country.TokenizerCharDecimal_characters1.Len]
Parent: country
0    Germany
1    Germany
2    Germany
3    Germany
4    Germany
5    Germany
6         US
7         US
8         US
9         US
Name: country.TokenizerCharDecimal_characters1, dtype: object
col: country.TokenizerCharDecimal_reversecharacters1  parent: country
Name : country.TokenizerCharDecimal_reversecharacters1
Size : 21
Dtype : object
Depth : 1
Children: [country.TokenizerCharDecimal_reversecharacters1.Len]
Parent: country
0    Germany
1    Germany
2    Germany
3    Germany
4    Germany
5    Germany
6       