In [1]:
import pandas as pd
import numpy as np
import scipy
from ColumnSet import ColumnSet
from MakeNumericColumns import MakeNumericColumns


import logging
import sys
logging.basicConfig(stream=sys.stdout, level=logging.INFO, datefmt='%H:%M:%S', format='%(asctime)s.%(msecs)03d - %(filename)s:%(lineno)d - %(message)s')

In [2]:
data1 = { 'country': ['Germany','Germany','Germany','Germany','Germany', 'Germany',
                     'US', 'US', 'US', 'US', 'US',
                     'UK', 'UK', 'UK', 'UK', 'UK', 
                     'LUX','LUX','LUX','LUX','LUX'],
         'currency':['EUR','EUR','EUR','EUR','EUR','MXN',
                     'USD','USD','USD','USD','USD',
                     'GBP','GBP','GBP','GBP','GBP',
                     'EUR','EUR','EUR','EUR','EUR'],
         'manyvalues':['A', 'A', 'B', 'B', 'C', 'C', 'D', 'D', 'E', 'E', 'E', 'K', 'L', 'M', 'N', 'O',
                      'Z', 'Z', 'Z', 'Z', 'Y'],
         'rand': [ np.random.uniform(100,200) for _ in range(21) ],
         'linear': [ x for x in range(21) ],
        'city': ['Frankfurt'] * 6 + ['LA'] * 5 + ['London'] * 5+  ['Luxembourg'] * 5}
data1 = pd.DataFrame(data1) 

cs = ColumnSet(data1)


mnc = MakeNumericColumns()

In [3]:

for column in cs.inputcolumns:
        print(mnc.Process(column))
        

[0 0 0 0 0 0 3 3 3 3 3 2 2 2 2 2 1 1 1 1 1]
[0 0 0 0 0 2 3 3 3 3 3 1 1 1 1 1 0 0 0 0 0]
[ 0  0  1  1  2  2  3  3  4  4  4  5  6  7  8  9 11 11 11 11 10]
[197.73934311 110.33324656 141.49694921 184.31724171 108.46969671
 139.25272078 151.21189695 153.46176893 187.76389336 137.53698367
 159.88652566 116.50373679 138.27690313 179.68117332 134.14118695
 161.89474101 178.55310843 165.02246245 176.74003862 163.09277384
 151.99074248]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[0 0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3]
