In [1]:
import pandas as pd
import numpy as np
import scipy

from TrainPredictSelf import TrainPredictSelf
from InterpretPredictions import InterpretPredictions


import logging
import sys
logging.basicConfig(stream=sys.stdout, level=logging.INFO, datefmt='%H:%M:%S', format='%(asctime)s.%(msecs)03d - %(filename)s:%(lineno)d - %(message)s')

In [2]:
data1 = { 'country': ['Germany','Germany','Germany','Germany','Germany', 'Germany',
                     'US', 'US', 'US', 'US', 'US',
                     'UK', 'UK', 'Germany', 'UK', 'UK', 
                     'LUX','LUX','LUX','LUX','LUX'],
         'currency':['EUR','EUR','EUR','EUR','EUR','MXN',
                     'USD','USD','USD','USD','USD',
                     'GBP','GBP','GBP','GBP','GBP',
                     'EUR','EUR','EUR','EUR','EUR'],
         'manyvalues':['A', 'A', 'B', 'B', 'C', 'C', 'D', 'D', 'E', 'E', 'E', 'K', 'L', 'M', 'N', 'O',
                      'Z', 'Z', 'Z', 'Z', 'Y'],
         'rand': [ np.random.uniform(100,200) for _ in range(21) ],
         'linear': [ x for x in range(21) ],
         'city': ['Frankfurt am Main'] * 6 + ['Los Angeles'] * 5 + ['London'] * 5 + ['Luxembourg'] * 4 + ['Bad'] * 1}
data1 = pd.DataFrame(data1) 
print(data1)

    country currency manyvalues        rand  linear               city
0   Germany      EUR          A  181.878784       0  Frankfurt am Main
1   Germany      EUR          A  152.065372       1  Frankfurt am Main
2   Germany      EUR          B  164.740929       2  Frankfurt am Main
3   Germany      EUR          B  150.397973       3  Frankfurt am Main
4   Germany      EUR          C  153.819085       4  Frankfurt am Main
5   Germany      MXN          C  143.935280       5  Frankfurt am Main
6        US      USD          D  102.553462       6        Los Angeles
7        US      USD          D  152.606384       7        Los Angeles
8        US      USD          E  160.592225       8        Los Angeles
9        US      USD          E  159.678084       9        Los Angeles
10       US      USD          E  179.068798      10        Los Angeles
11       UK      GBP          K  107.479833      11             London
12       UK      GBP          L  114.048892      12             London
13  Ge

In [3]:
tps = TrainPredictSelf()

results_labels, results_proba = tps.Train(data1)

*** country ***
[[ 1.  0.  0. ...  4.  2.  9.]
 [ 1.  0.  0. ...  4.  2.  9.]
 [ 1.  0.  0. ...  4.  2.  9.]
 ...
 [ 1.  0.  0. ... 10.  0.  0.]
 [ 1.  0.  0. ... 10.  0.  0.]
 [ 1.  0.  0. ...  3.  0.  0.]]
[0 0 0 0 0 0 3 3 3 3 3 2 2 0 2 2 1 1 1 1 1]
*** currency ***
[[ 1.  0.  0. ...  4.  2.  9.]
 [ 1.  0.  0. ...  4.  2.  9.]
 [ 1.  0.  0. ...  4.  2.  9.]
 ...
 [ 0.  1.  0. ... 10.  0.  0.]
 [ 0.  1.  0. ... 10.  0.  0.]
 [ 0.  1.  0. ...  3.  0.  0.]]
[0 0 0 0 0 2 3 3 3 3 3 1 1 1 1 1 0 0 0 0 0]
*** manyvalues ***
[[ 1.  0.  0. ...  4.  2.  9.]
 [ 1.  0.  0. ...  4.  2.  9.]
 [ 1.  0.  0. ...  4.  2.  9.]
 ...
 [ 0.  1.  0. ... 10.  0.  0.]
 [ 0.  1.  0. ... 10.  0.  0.]
 [ 0.  1.  0. ...  3.  0.  0.]]
[ 0  0  1  1  2  2  3  3  4  4  4  5  6  7  8  9 11 11 11 11 10]
*** rand ***
[[ 1.  0.  0. ...  4.  2.  9.]
 [ 1.  0.  0. ...  4.  2.  9.]
 [ 1.  0.  0. ...  4.  2.  9.]
 ...
 [ 0.  1.  0. ... 10.  0.  0.]
 [ 0.  1.  0. ... 10.  0.  0.]
 [ 0.  1.  0. ...  3.  0.  0.]]
[4. 1. 3. 1. 2

In [4]:
ip = InterpretPredictions()
dfpredicted, dfprobas = ip.SinglePredictionPerCell(results_labels, results_proba)
print(dfpredicted)
print(dfprobas)

    country currency manyvalues        rand  linear               city
0   Germany      EUR          B  136.110398     2.0  Frankfurt am Main
1   Germany      EUR          B  185.345997     6.0  Frankfurt am Main
2   Germany      EUR          A  136.110398     2.0  Frankfurt am Main
3   Germany      EUR          C  156.423893     2.0  Frankfurt am Main
4   Germany      EUR          C  136.110398     2.0  Frankfurt am Main
5   Germany      EUR          B  156.423893     2.0             London
6        UK      USD          E  156.423893    10.0        Los Angeles
7        US      USD          E  110.103677     6.0        Los Angeles
8        US      USD          E  156.423893    10.0        Los Angeles
9        US      USD          E  185.345997    10.0        Los Angeles
10       US      USD          E  156.423893    10.0        Los Angeles
11       UK      GBP          L  110.103677    14.0             London
12       UK      GBP          N  110.103677    14.0             London
13    

In [5]:
dfConfidence =ip.Confidence(results_proba)
print(dfConfidence)

     country  currency  manyvalues      rand    linear      city
0   0.915435  0.883065    0.545371  0.314351  0.563485  0.795991
1   0.856967  0.879134    0.532579  0.626513  0.308484  0.842292
2   0.862789  0.916594    0.472867  0.781784  0.335233  0.838433
3   0.873800  0.906142    0.408103  0.686666  0.381606  0.844724
4   0.856967  0.892842    0.115570  0.915668  0.832833  0.861811
5   0.275137  0.223807    0.023767  0.335512  0.492360  0.014078
6   0.061912  0.804506    0.022456  0.727759  0.357169  0.643838
7   0.839682  0.864570    0.258602  0.245499  0.425388  0.780131
8   0.859788  0.821259    0.244973  0.836791  0.680497  0.848812
9   0.837957  0.815249    0.465758  0.598185  0.759084  0.778380
10  0.518053  0.835347    0.440932  0.303203  0.614121  0.736988
11  0.750826  0.786536    0.148297  0.718289  0.874582  0.843073
12  0.766028  0.828770    0.056313  0.536606  0.772112  0.767701
13  0.715318  0.070934    0.112429  0.125120  0.162773  0.513097
14  0.810197  0.764706   

In [6]:
dfBoolDifferences = ip._BoolDifferencesConfidentPredictionCorrect(data1, results_labels, dfpredicted, results_proba, dfConfidence)
print(dfBoolDifferences)

    country  currency  manyvalues   rand  linear   city
0     False     False       False  False   False  False
1     False     False       False  False   False  False
2     False     False       False  False   False  False
3     False     False       False  False   False  False
4     False     False       False   True   False  False
5     False     False       False  False   False  False
6     False     False       False  False   False  False
7     False     False       False  False   False  False
8     False     False       False  False   False  False
9     False     False       False  False   False  False
10    False     False       False  False   False  False
11    False     False       False  False    True  False
12    False     False       False  False   False  False
13     True     False       False  False   False  False
14    False     False       False  False   False  False
15    False     False       False  False   False  False
16    False     False       False  False   False

In [7]:
dfBoolDifferences = ip._BoolDifferencesConfidentObservedWrong(data1, results_labels, dfpredicted, results_proba, dfConfidence)
print(dfBoolDifferences)

country
[0.9394061  0.89572453 0.89799637 0.9095732  0.89572453 0.49212286
 0.43054742 0.8946641  0.90745926 0.8922944  0.7170551  0.81496775
 0.8268907  0.07108278 0.858896   0.3563557  0.17935576 0.8798115
 0.89693224 0.86969054 0.10916653]
currency
[0.9198182  0.9203229  0.9438574  0.93757004 0.92872375 0.
 0.85870206 0.90205026 0.8777324  0.8766775  0.8844211  0.8489144
 0.88310313 0.3166941  0.8420052  0.8420052  0.90821254 0.89738923
 0.92779094 0.95734507 0.8321888 ]
manyvalues
[0.         0.         0.05160603 0.07304673 0.25192857 0.17049932
 0.15566593 0.06581733 0.3735225  0.6220035  0.50238043 0.
 0.         0.         0.         0.         0.8042178  0.79993546
 0.76301116 0.8013292  0.        ]
rand
[0.00303409 0.00647443 0.01764837 0.06852485 0.01075898 0.15631852
 0.01401583 0.10801718 0.00713899 0.06062926 0.01573579 0.79608417
 0.7338178  0.07398673 0.16403049 0.01072621 0.14812757 0.04498965
 0.75271505 0.15374565 0.02887568]
linear
[0.66256416 0.2963621  0.4946536  

In [8]:
dfBoolDifferences =  ip.boolDifferences(data1, results_labels, results_proba)
print(dfBoolDifferences)

country
[0.9394061  0.89572453 0.89799637 0.9095732  0.89572453 0.49212286
 0.43054742 0.8946641  0.90745926 0.8922944  0.7170551  0.81496775
 0.8268907  0.07108278 0.858896   0.3563557  0.17935576 0.8798115
 0.89693224 0.86969054 0.10916653]
currency
[0.9198182  0.9203229  0.9438574  0.93757004 0.92872375 0.
 0.85870206 0.90205026 0.8777324  0.8766775  0.8844211  0.8489144
 0.88310313 0.3166941  0.8420052  0.8420052  0.90821254 0.89738923
 0.92779094 0.95734507 0.8321888 ]
manyvalues
[0.         0.         0.05160603 0.07304673 0.25192857 0.17049932
 0.15566593 0.06581733 0.3735225  0.6220035  0.50238043 0.
 0.         0.         0.         0.         0.8042178  0.79993546
 0.76301116 0.8013292  0.        ]
rand
[0.00303409 0.00647443 0.01764837 0.06852485 0.01075898 0.15631852
 0.01401583 0.10801718 0.00713899 0.06062926 0.01573579 0.79608417
 0.7338178  0.07398673 0.16403049 0.01072621 0.14812757 0.04498965
 0.75271505 0.15374565 0.02887568]
linear
[0.66256416 0.2963621  0.4946536  