In [1]:
import pandas as pd
import numpy as np
import scipy

from TrainPredictSelf import TrainPredictSelf


import logging
import sys
logging.basicConfig(stream=sys.stdout, level=logging.INFO, datefmt='%H:%M:%S', format='%(asctime)s.%(msecs)03d - %(filename)s:%(lineno)d - %(message)s')

In [2]:
data1 = { 'country': ['Germany','Germany','Germany','Germany','Germany', 'Germany',
                     'US', 'US', 'US', 'US', 'US',
                     'UK', 'UK', 'Germany', 'UK', 'UK', 
                     'LUX','LUX','LUX','LUX','LUX'],
         'currency':['EUR','EUR','EUR','EUR','EUR','MXN',
                     'USD','USD','USD','USD','USD',
                     'GBP','GBP','GBP','GBP','GBP',
                     'EUR','EUR','EUR','EUR','EUR'],
         'manyvalues':['A', 'A', 'B', 'B', 'C', 'C', 'D', 'D', 'E', 'E', 'E', 'K', 'L', 'M', 'N', 'O',
                      'Z', 'Z', 'Z', 'Z', 'Y'],
         'rand': [ np.random.uniform(100,200) for _ in range(21) ],
         'linear': [ x for x in range(21) ],
         'city': ['Frankfurt am Main'] * 6 + ['Los Angeles'] * 5 + ['London'] * 5 + ['Luxembourg'] * 4 + ['Bad'] * 1}
data1 = pd.DataFrame(data1) 

In [3]:
tps = TrainPredictSelf()

tps.Train(data1)

*** country ***
mode : classifier
actuals:
[0 0 0 0 0 0 3 3 3 3 3 2 2 0 2 2 1 1 1 1 1]
predictions:
[0 0 0 0 0 0 3 3 3 3 3 2 2 2 2 1 1 1 1 1 1]
probabilities
[0.90647906 0.8767009  0.9299957  0.87877136 0.9040104  0.76896733
 0.7984177  0.85068935 0.78105885 0.8662943  0.84138083 0.61330444
 0.55046695 0.886094   0.4821883  0.46139678 0.88189834 0.7820789
 0.744133   0.9006625  0.46556124]
*** currency ***
mode : classifier
actuals:
[0 0 0 0 0 2 3 3 3 3 3 1 1 1 1 1 0 0 0 0 0]
predictions:
[0 0 0 0 0 0 3 3 3 3 3 1 1 0 1 1 0 0 0 0 0]
probabilities
[0.71335816 0.91472167 0.7604107  0.9195697  0.713994   0.83377445
 0.78423065 0.90134066 0.74198097 0.88626564 0.7871258  0.8092603
 0.85376686 0.4140242  0.8543477  0.76488525 0.9312955  0.94787174
 0.65806115 0.9357647  0.8723464 ]
*** manyvalues ***
mode : classifier
actuals:
[ 0  0  1  1  2  2  3  3  4  4  4  5  6  7  8  9 11 11 11 11 10]
predictions:
[ 1  1  0  2  1  3  4  4  4  4  4  6  5  2  9  4 11 11 11 11 11]
probabilities
[0.5714691