In [1]:
import pandas as pd
import numpy as np
import scipy

from TrainPredictSelf import TrainPredictSelf


import logging
import sys
logging.basicConfig(stream=sys.stdout, level=logging.INFO, datefmt='%H:%M:%S', format='%(asctime)s.%(msecs)03d - %(filename)s:%(lineno)d - %(message)s')

In [2]:
data1 = { 'country': ['Germany','Germany','Germany','Germany','Germany', 'Germany',
                     'US', 'US', 'US', 'US', 'US',
                     'UK', 'UK', 'Germany', 'UK', 'UK', 
                     'LUX','LUX','LUX','LUX','LUX'],
         'currency':['EUR','EUR','EUR','EUR','EUR','MXN',
                     'USD','USD','USD','USD','USD',
                     'GBP','GBP','GBP','GBP','GBP',
                     'EUR','EUR','EUR','EUR','EUR'],
         'manyvalues':['A', 'A', 'B', 'B', 'C', 'C', 'D', 'D', 'E', 'E', 'E', 'K', 'L', 'M', 'N', 'O',
                      'Z', 'Z', 'Z', 'Z', 'Y'],
         'rand': [ np.random.uniform(100,200) for _ in range(21) ],
         'linear': [ x for x in range(21) ],
         'city': ['Frankfurt am Main'] * 6 + ['Los Angeles'] * 5 + ['London'] * 5 + ['Luxembourg'] * 4 + ['Bad'] * 1}
data1 = pd.DataFrame(data1) 
print(data1)

    country currency manyvalues        rand  linear               city
0   Germany      EUR          A  127.911260       0  Frankfurt am Main
1   Germany      EUR          A  178.159043       1  Frankfurt am Main
2   Germany      EUR          B  108.233328       2  Frankfurt am Main
3   Germany      EUR          B  153.251594       3  Frankfurt am Main
4   Germany      EUR          C  183.168243       4  Frankfurt am Main
5   Germany      MXN          C  112.664358       5  Frankfurt am Main
6        US      USD          D  124.986450       6        Los Angeles
7        US      USD          D  139.524108       7        Los Angeles
8        US      USD          E  104.193841       8        Los Angeles
9        US      USD          E  176.269921       9        Los Angeles
10       US      USD          E  133.653101      10        Los Angeles
11       UK      GBP          K  162.970998      11             London
12       UK      GBP          L  116.958109      12             London
13  Ge

In [3]:
tps = TrainPredictSelf()

results_labels, results_proba = tps.Train(data1)

*** country ***
[[ 1.  0.  0. ...  4.  2.  9.]
 [ 1.  0.  0. ...  4.  2.  9.]
 [ 1.  0.  0. ...  4.  2.  9.]
 ...
 [ 1.  0.  0. ... 10.  0.  0.]
 [ 1.  0.  0. ... 10.  0.  0.]
 [ 1.  0.  0. ...  3.  0.  0.]]
[0 0 0 0 0 0 3 3 3 3 3 2 2 0 2 2 1 1 1 1 1]
*** currency ***
[[ 1.  0.  0. ...  4.  2.  9.]
 [ 1.  0.  0. ...  4.  2.  9.]
 [ 1.  0.  0. ...  4.  2.  9.]
 ...
 [ 0.  1.  0. ... 10.  0.  0.]
 [ 0.  1.  0. ... 10.  0.  0.]
 [ 0.  1.  0. ...  3.  0.  0.]]
[0 0 0 0 0 2 3 3 3 3 3 1 1 1 1 1 0 0 0 0 0]
*** manyvalues ***
[[ 1.  0.  0. ...  4.  2.  9.]
 [ 1.  0.  0. ...  4.  2.  9.]
 [ 1.  0.  0. ...  4.  2.  9.]
 ...
 [ 0.  1.  0. ... 10.  0.  0.]
 [ 0.  1.  0. ... 10.  0.  0.]
 [ 0.  1.  0. ...  3.  0.  0.]]
[ 0  0  1  1  2  2  3  3  4  4  4  5  6  7  8  9 11 11 11 11 10]
*** rand ***
[[ 1.  0.  0. ...  4.  2.  9.]
 [ 1.  0.  0. ...  4.  2.  9.]
 [ 1.  0.  0. ...  4.  2.  9.]
 ...
 [ 0.  1.  0. ... 10.  0.  0.]
 [ 0.  1.  0. ... 10.  0.  0.]
 [ 0.  1.  0. ...  3.  0.  0.]]
[1. 4. 0. 2. 4

In [4]:
dfLabels, dfProbas = tps.SinglePredictionPerCell(results_labels, results_proba)
print(dfLabels)
print(dfProbas)

    country currency manyvalues        rand  linear               city
0   Germany      EUR          B  186.851059     2.0  Frankfurt am Main
1   Germany      EUR          B  123.365685     6.0  Frankfurt am Main
2   Germany      EUR          C  186.851059     2.0  Frankfurt am Main
3   Germany      EUR          C  123.365685     2.0  Frankfurt am Main
4   Germany      EUR          Y  110.575975     2.0  Frankfurt am Main
5   Germany      EUR          D  186.851059     2.0  Frankfurt am Main
6        US      USD          E  110.575975     6.0        Los Angeles
7        US      USD          E  110.575975    10.0        Los Angeles
8        US      USD          D  186.851059     6.0        Los Angeles
9        US      USD          D  142.066327    10.0        Los Angeles
10       US      USD          D  186.851059     6.0        Los Angeles
11       UK      GBP          E  123.365685    14.0             London
12       UK      GBP          E  165.314657    14.0             London
13    

In [5]:
dfConfidence =tps.Confidence(results_proba)
print(dfConfidence)

     country  currency  manyvalues      rand    linear      city
0   0.941996  0.835517    0.034651  0.869575  0.468597  0.806801
1   0.766996  0.888597    0.612253  0.094200  0.552763  0.799698
2   0.931314  0.742155    0.373356  0.889319  0.114538  0.890739
3   0.925377  0.926382    0.027808  0.010172  0.201620  0.806801
4   0.760504  0.874800    0.012281  0.251624  0.763111  0.862040
5   0.764790  0.222583    0.025354  0.355361  0.850403  0.001099
6   0.213171  0.864182    0.059723  0.619445  0.080886  0.832663
7   0.795731  0.851889    0.241144  0.667760  0.427790  0.842394
8   0.347272  0.622946    0.378394  0.618468  0.879791  0.845227
9   0.874840  0.838739    0.051265  0.640539  0.110461  0.808398
10  0.842582  0.795902    0.057730  0.152868  0.708140  0.844493
11  0.674126  0.845575    0.154787  0.686185  0.827930  0.844163
12  0.253672  0.798648    0.082812  0.157144  0.740690  0.828488
13  0.830722  0.189472    0.013475  0.794603  0.007900  0.688990
14  0.417984  0.857068   

In [6]:
dfBoolDifferences = tps.BoolDifferencesConfidentPredictionCorrect(results_labels, dfLabels, results_proba, dfConfidence)
print(dfBoolDifferences)

    country  currency  manyvalues   rand  linear   city
0     False     False       False  False   False  False
1     False     False       False  False   False  False
2     False     False       False  False   False  False
3     False     False       False  False   False  False
4     False     False       False  False   False  False
5     False     False       False  False   False  False
6     False     False       False  False   False  False
7     False     False       False  False   False  False
8     False     False       False  False   False  False
9     False     False       False  False   False  False
10    False     False       False  False   False  False
11    False     False       False  False   False  False
12    False     False       False  False   False  False
13     True     False       False  False   False  False
14    False     False       False  False   False  False
15    False     False       False  False   False  False
16    False     False       False  False   False

In [7]:
dfBoolDifferences = tps.BoolDifferencesConfidentObservedWrong(results_labels, dfLabels, results_proba, dfConfidence)
print(dfBoolDifferences)

country
[0.95890737 0.84106475 0.9530629  0.94720376 0.82553273 0.850539
 0.58878666 0.87445825 0.6310743  0.9168923  0.8929601  0.7670656
 0.54982615 0.04164584 0.23216158 0.2018417  0.87187576 0.84002286
 0.84482825 0.834097   0.27673712]
currency
[0.8867519  0.92329836 0.84479845 0.9478052  0.91124856 0.
 0.90142995 0.89361155 0.7596733  0.8881507  0.85391647 0.8909221
 0.86484563 0.4360162  0.8963832  0.8587117  0.93058234 0.9476856
 0.9528232  0.95971644 0.85765624]
manyvalues
[0.10420685 0.00989445 0.09821734 0.16146968 0.17035294 0.14331774
 0.19298545 0.17608087 0.08624526 0.1253203  0.30708787 0.
 0.         0.         0.         0.         0.79871064 0.82930833
 0.78420824 0.73207396 0.        ]
rand
[0.00456618 0.09294719 0.01119578 0.00847669 0.03211892 0.16690587
 0.00124254 0.07238246 0.03947166 0.02406278 0.21661486 0.00942173
 0.19126292 0.05932756 0.00663401 0.0371847  0.79495704 0.9101584
 0.00778761 0.10423066 0.55062824]
linear
[0.70231444 0.1359479  0.4684123  0.53

In [8]:
dfBoolDifferences =  tps.boolDifferencesCombined(results_labels, dfLabels, results_proba, dfConfidence)
print(dfBoolDifferences)

country
[0.95890737 0.84106475 0.9530629  0.94720376 0.82553273 0.850539
 0.58878666 0.87445825 0.6310743  0.9168923  0.8929601  0.7670656
 0.54982615 0.04164584 0.23216158 0.2018417  0.87187576 0.84002286
 0.84482825 0.834097   0.27673712]
currency
[0.8867519  0.92329836 0.84479845 0.9478052  0.91124856 0.
 0.90142995 0.89361155 0.7596733  0.8881507  0.85391647 0.8909221
 0.86484563 0.4360162  0.8963832  0.8587117  0.93058234 0.9476856
 0.9528232  0.95971644 0.85765624]
manyvalues
[0.10420685 0.00989445 0.09821734 0.16146968 0.17035294 0.14331774
 0.19298545 0.17608087 0.08624526 0.1253203  0.30708787 0.
 0.         0.         0.         0.         0.79871064 0.82930833
 0.78420824 0.73207396 0.        ]
rand
[0.00456618 0.09294719 0.01119578 0.00847669 0.03211892 0.16690587
 0.00124254 0.07238246 0.03947166 0.02406278 0.21661486 0.00942173
 0.19126292 0.05932756 0.00663401 0.0371847  0.79495704 0.9101584
 0.00778761 0.10423066 0.55062824]
linear
[0.70231444 0.1359479  0.4684123  0.53